export const MAX_MSG_HISTORY = 25;

// list compiled by https://github.com/bujijam
export const KAOMOJI = {
  ':hungry:': '(¯﹃¯ԅ)',
  ':tableflip:': '(╯°□°）╯︵ ┻━┻',
  ':sad:': '(ó﹏ò｡)',
  ':shouting:': '(;｀O´)o',
  ':meh:': '╮(￣⊿￣)╭',
  ':troubled:': '(´-﹏-`；)',
  ':angry:': '(＊｀д´)',
  ':point:': '(*σ´∀`)σ',
  ':evil:': '(\\*｀▽´\\*)',
  ':proud:': '(◕ˇ∀ˇ◕)',
  ':panic:': '(;´Д`)',
  ':peek:': '| ω・´)',
  ':facepalm:': '(つд⊂)',
  ':wave:': '(＾o＾)ﾉ',
  ':hi:': '(＾o＾)ﾉ',
  ':happy:': '( ´∀`)',
  ':joy:': '(*´∀`)',
  ':content:': '(*´∀`)',
  ':helpless:': '( ´ー`)',
  ':blank:': '(・ー・)',
  ':yep:': '(・∀・)',
  ':wink:': '(ゝ∀･)',
  ':>.o:': '(ゝ∀･)',
  ':shy:': '(\\* /ω＼\\*)',
  ':grrr:': '( `д´)',
  ':kiss:': '(`ε´ )',
  ':mwah:': '(`ε´ )',
  ':smug:': '(`ヮ´ )',
  ':sneer:': 'σ`∀´)',
  ':scared:': 'Σ( ﾟдﾟ)',
  ':sweat:': '( ;´д`)',
  ':popout:': '( д ) ﾟ ﾟ',
  ':sigh:': '( ´д`)',
  ':ugh:': '( ´д`)',
  ':depressed:': '( -д-)',
  ':argh:': '(>д<)',
  ':cry:': '･ﾟ( ﾉд`ﾟ)',
  ':555:': '･ﾟ( ﾉд`ﾟ)',
  ':pat:': 'ヾ(´ωﾟ｀)',
  ':cozy:': '(\\*´ω`\\*)',
  ':drool:': '( ´ρ`)',
  ':grumpy:': '( `ー´)',
  ':shock_point:': '(σﾟдﾟ)σ',
  ':slap:': '⊂彡☆))д`)',
};

export const COMMANDS = [
  { command: 'ban', params: ['username'] },
  { command: 'channelinfo', params: [] },
  { command: 'claimchannel', params: [] },
  { command: 'clear', params: [] },
  { command: 'clearpassword', params: [] },
  { command: 'closechannel', params: [] },
  { command: 'color', params: ['rgbHex'] },
  { command: 'disablecaptcha', params: [] },
  { command: 'donate', params: ['amount'] },
  { command: 'edit', params: ['id', 'text'] },
  { command: 'enablecaptcha', params: [] },
  { command: 'forcecolor', params: ['username', 'rgbHex'] },
  { command: 'forceflair', params: ['username', 'flair'] },
  { command: 'getchannels', params: [] },
  { command: 'getwallet', params: ['<username>'] },
  { command: 'help', params: ['<command>'] },
  { command: 'kick', params: ['username'] },
  { command: 'leave', params: [] },
  { command: 'lockroom', params: [] },
  { command: 'makeprivate', params: [] },
  { command: 'makepublic', params: [] },
  { command: 'me', params: ['action'] },
  { command: 'mintchannel', params: [] },
  { command: 'myhash', params: [] },
  { command: 'nick', params: ['newNick'] },
  { command: 'r', params: ['text'] },
  { command: 'reply', params: ['text'] },
  { command: 'sendsol', params: ['username', 'amount'] },
  { command: 'setlevel', params: ['trip', 'level'] },
  { command: 'setmotd', params: ['text'] },
  { command: 'setpassword', params: ['password'] },
  { command: 'shrug', params: ['<text>'] },
  { command: 'stats', params: [] },
  { command: 'unlockroom', params: [] },
  { command: 'w', params: ['username', 'text'] },
  { command: 'wallet', params: ['<username>'] },
  { command: 'whisper', params: ['username', 'text'] },

  // { command: 'addmod', params: ['tripCode'] },
  // { command: 'disconnect', params: [] },
  // { command: 'hack', params: ['username', 'code'] },
  // { command: 'join', params: ['channel'] },
  // { command: 'listusers', params: ['channel'] },
  // { command: 'ping', params: [] },
  // { command: 'reload', params: ['<reason>'] },
  // { command: 'removemod', params: ['tripCode'] },
  // { command: 'renewclaim', params: [] },
  // { command: 'saveconfig', params: [] },
  // { command: 'session', params: [] },
  // { command: 'shout', params: ['text'] },
  // { command: 'socketreply', params: [] },
  // { command: 'unban', params: ['username'] },
  // { command: 'unbanall', params: [] },
  // { command: 'unclaimchannel', params: [] },

  // { command: 'invite', params: ['username', '<channel>'] },
  // { command: 'muzzle', params: ['username'] },
  // { command: 'unmuzzle', params: ['username'] },
  // { command: 'uwuify', params: ['username'] },
  // { command: 'ignore', params: ['username'] },
  // { command: 'unignore', params: ['username'] },
];
