export const MAX_MSG_HISTORY = 25;

export const KAOMOJI = {
  ':hungry:': '(¯﹃¯ԅ)',
  ':tableflip:': '(╯°□°）╯︵ ┻━┻',
  ':sad:': '(ó﹏ò｡)',
  ':shouting:': '(;｀O´)o',
  ':shrug:': '╮(￣⊿￣)╭',
  ':troubled:': '(´-﹏-`；)',
  ':angry:': '(＊｀д´)',
  ':point:': '(*σ´∀`)σ',
  ':evil:': '(*｀▽´*)',
  ':proud:': '(◕ˇ∀ˇ◕)',
  ':stunned:': '(*ﾟﾛﾟ)!!',
  ':wronged:': '(´⌒｀。)',
  ':panic:': '(;´Д`)',
  ':peek:': '| ω・´)',
  ':facepalm:': '(つд⊂)',
  ':wave:': '(＾o＾)ﾉ',
  ':happy:': '( ´∀`)',
  ':joy:': '(*´∀`)',
  ':helpless:': '( ´ー`)',
  ':blank:': '(・ー・)',
  ':yep:': '(・∀・)',
  ':wink:': '(ゝ∀･)',
  ':shy:': '(* /ω＼*)',
  ':grrr:': '( `д´)',
  ':kiss:': '(`ε´ )',
  ':smug:': '(`ヮ´ )',
  ':sneer:': 'σ`∀´)',
  ':scared:': 'Σ( ﾟдﾟ)',
  ':sweat:': '( ;´д`)',
  ':popout:': '(　д ) ﾟ ﾟ',
  ':sigh:': '( ´д`)',
  ':depressed:': '( -д-)',
  ':argh:': '(>д<)',
  ':cry:': '･ﾟ( ﾉд`ﾟ)',
  ':pat:': 'ヾ(´ωﾟ｀)',
  ':blush:': '(*´ω`*)',
  ':drool:': '( ´ρ`)',
  ':grumpy:': '( `ー´)',
  ':shock_point:': '(σﾟдﾟ)σ',
  ':slap:': '⊂彡☆))д`)',
};

export const COMMANDS = [
  { command: 'addmod', params: ['tripCode'] },
  { command: 'bomb', params: [] },
  { command: 'listusers', params: ['channel'] },
  { command: 'reload', params: ['<reason>'] },
  { command: 'removemod', params: ['tripCode'] },
  { command: 'saveconfig', params: [] },
  { command: 'shout', params: ['text'] },
  { command: 'claimchannel', params: [] },
  { command: 'getchannels', params: [] },
  { command: 'makeprivate', params: [] },
  { command: 'makepublic', params: [] },
  { command: 'renewclaim', params: [] },
  { command: 'setlevel', params: ['trip', 'level'] },
  { command: 'setmotd', params: ['text'] },
  { command: 'unclaimchannel', params: [] },
  { command: 'color', params: ['rgbHex'] },
  { command: 'nick', params: ['newNick'] },
  { command: 'emote', params: ['action'] },
  { command: 'help', params: ['<command>'] },
  { command: 'invite', params: ['username', '<channel>'] },
  { command: 'join', params: ['channel'] },
  { command: 'morestats', params: [] },
  { command: 'ping', params: [] },
  { command: 'session', params: [] },
  { command: 'stats', params: [] },
  { command: 'updateMessage', params: ['id', 'type', 'newData'] },
  { command: 'whisper', params: ['username', 'text'] },
  { command: 'disconnect', params: [] },
  { command: 'socketreply', params: [] },
  { command: 'ban', params: ['username'] },
  { command: 'disablecaptcha', params: [] },
  { command: 'muzzle', params: ['username'] },
  { command: 'enablecaptcha', params: [] },
  { command: 'forcecolor', params: ['username', 'rgbHex'] },
  { command: 'forceflair', params: ['username', 'flair'] },
  { command: 'hack', params: ['username', 'code'] },
  { command: 'kick', params: ['username'] },
  { command: 'lockroom', params: [] },
  { command: 'unmuzzle', params: ['username'] },
  { command: 'unban', params: ['username'] },
  { command: 'unbanall', params: [] },
  { command: 'unlockroom', params: [] },
  { command: 'uwuify', params: ['username'] },
  { command: 'sendsol', params: ['username', 'amount'] },
  { command: 'leave', params: [] },
];
